extends: standard

overrides:
  -
    files: [ '*.mjs' ]
    rules:
      no-restricted-globals: [ 2, require, __dirname ]
  -
    files: [ 'test/**' ]
    env: { mocha: true }
  -
    files: [ 'lib/**', 'index.mjs' ]
    parserOptions: { ecmaVersion: 2015 }

ignorePatterns:
  - dist/
  - lib/data/light.mjs
  - lib/data/full.mjs

rules:
  camelcase: 0
